baseurl = "https://reconlearn-ld.netlify.com/"
theme = "hugo-casper-two"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "itsalocke"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
# Ignore the following extensions
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$","^README"]
paginate        = 6
[permalinks]
  post = "/post/:slug/"
[params]
  title = "RECON learn"
  # Use custom.css for your custom styling
  style = "default"
  subtitle = "RECON's teaching platform"
  copyright = "©2017 Thibaut Jombart"
  description = "For more about the R Epidemics Consortium (RECON), visit our website: https://repidemicsconsortium.org"
  singleViewStyle = "casper"
  pageNotFoundTitle = "404 - Page not found"
  customCSS = ["css/custom.css"]
  
  email         = "thibautjombart@gmail.com"
  twitterName    = "teebzr"
  
  logo = "img/logo/learn.png"
  orgName = "RECON"
  orgWebsite = "https://repidemicsconsortium.org"
  orgDescription = "For more about the R Epidemics Consortium (RECON), visit our website: https://repidemicsconsortium.org"
  authorAvatar = "img/user.png"

  showSupport = true


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200
  
[[menu.main]]
  name = "Practicals"
  url = "/categories/practicals"
  weight = 99
  
[[menu.main]]
  name = "Lectures"
  url = "/categories/lectures"
  weight = 99

  
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90
  
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 89
  
[[menu.main]]
  name = "Sample"
  url = "/sample"
  weight = 87